### ISSUE TITLE
[Feature req] Add no-filter option for matching tiles in EPT query

### ISSUE THREAD

**Issue by jpolchlo** [PDAL/PDAL#2959]
There is an occasional need to acquire a multiresolution sample of points, constructed such that we have an approximate representation of the whole point set that is more precise in a target area.  A key application of this is when generating a Delaunay triangulation for a point cloud.  Delaunay triangulations have no guarantees of locality; triangles can have a maximum side length as large as the maximum distance between points in the whole point set.

At present, when selecting points from an EPT catalog, one has control over the maximum tree depth to traverse (via the resolution parameter), and the bounding box of returned points.  The bounding box is a strict parameter, meaning that when `bounds` is specified, no points will be returned outside the query region.  This is a problem if one is constructing a triangulation where, for example, the bounding box overlaps the convex hull of the points, but there are not any points in the query region.  One would, in this case, expect triangles to overlap the bounds region, but there will be no triangles generated at all.

EPTs allow for a multiresolution sample to be made covering the whole geometric extent of the point cloud, while devoting more points to an area of interest.  The proposed solution is to return the content of any tiles whose extent intersects the query region—up to the maximum tree depth inferred from the resolution parameter.  Given this, the possibility of catastrophic failure of a triangulation step is nearly eliminated, and the size of point sample required to achieve this result is resonably constrained.

The proposal is to specify a flag that only operates in conjunction with `bounds` to select the tiles which intersect the bounding box.  This would be a simple addition to the EPT tree walker, but a nontrivial, redundant effort for an independent developer.

**Comment by connormanning** [comment]
I'm not sure I fully understand what you are asking.

Currently, the EPT reader, when given a `bounds` option, 1) selects all tiles that overlap the bounds and downloads those tiles.  Then 2) for each point within those tiles, each point is tested against the bounds and points that are not contained by the bounds are discarded.

Am I correct to say that you're asking for an option to disable this second step, so that *all* points from overlapping tiles are included even if those points themselves are not contained by the bounds?

**Comment by jpolchlo** [comment]
Indeed, that is exactly what we're asking for.  A very simple feature.

**Comment by hobu** [comment]
For clarification, you want all the points in this picture returned for a query box that is the inner most high density `bounds`?

![image](https://user-images.githubusercontent.com/87751/75926343-ff6c8f80-5e2f-11ea-94c9-0c5fc3a4d924.png)

**Comment by jpolchlo** [comment]
Can't say for :100:, given that I don't know exactly how the image was generated, but that looks like what I'm after.

**Comment by jpolchlo** [comment]
Note: It may be the case that we're better off rolling our own solution, since this may be of limited interest to other parties.

**Comment by hobu** [comment]
I'm interested in supporting the scenario without disrupting or changing the behavior of how ``bounds`` is used and specified as a cropping object. 

What if we added a ``nadir`` option that was specified as a bounds but did not imply a crop? I think the toughest bit here is naming the thing... 😄

**Comment by jpolchlo** [comment]
We're going though the same problem.  Can't seem to concisely describe what the hell this operation is!  `select`?  `containing`?  No clue.

**Comment by echeipesh** [comment]
Why `nadir` : things directly under? Kind of works.
I will throw in `intersecting` keyword with same format as bounds because we're returning tiles that only intersect the bounding box but not filtering down to it.

**Comment by connormanning** [comment]
I've pushed a branch that has this behavior called `ept-reader-cull-to-selection`.  I've simply called the option `cull_to_selection`, so you can set this to `false` to skip the secondary culling of points to the bounds/polygon selection.

> Note: It may be the case that we're better off rolling our own solution, since this may be of limited interest to other parties.

I tend to agree with this and think this probably belongs on a fork - the behavior here is pretty confusing for the general user, since you specify bounds but it is purposely not fully respected.

**Comment by jpolchlo** [comment]
I've been thinking about this a bit, and I'd like to present an argument: For those parties interested in generating a triangulation using PDAL, they may find themselves in the position of having "done everything right", and are still getting wildly incorrect results with no recourse except to implement a nontrivial feature, or to check out what will likely become a forgotten branch that hasn't been updated in a long time.  What we're asking for would be useful to anyone trying to interpolate data over a TIN.

If the option is odd and/or confusing, perhaps consider keeping it undocumented for now, until perhaps another future user finds themselves in a similar position.  Though I understand if you'd wrinkle your nose at that prospect.

**Comment by abellgithub** [comment]
It's unclear to me what the issue is WRT a TIN and this change.  Perhaps you can explain.  I don't know why this change would lead to or eliminate "wildly incorrect results."

**Comment by jpolchlo** [comment]
This is explained in the first post, but if the query region is in the convex hull of the point set but not intersecting the point set, then the result will be an empty triangulation, which is as bad a result as possible.  With the no-cull option, one will, at the very least, get a coarse approximation of the whole point set by grabbing the 0-0-0-0 tree cell (usually more than this).  Thus, there will at least be some coverage by the triangulation of the area of interest.

**Comment by connormanning** [comment]
> then the result will be an empty triangulation, which is as bad a result as possible

Can you elaborate on this a bit more, because if there are truly no points in the requested region, this seems like the appropriate result in this case.  If you really want data over no-data regions, what about the following:

Could you not get a better result, with more control over what you are getting in response, by perhaps making a pyramid of requests at different resolutions?  For example (with made-up numbers):
- query region at 0.1 resolution
- 2x the query region at 1 resolution
- 8x the query region at 50 resolution
- Entire dataset at 1000 resolution - just the `0-0-0-0` node typically.

You could get some guarantees on what comes back this way and have more control over your TIN input data - rather than simply accepting what comes back from the `no-cull` query.  Keep in mind that this `no-cull` result is essentially arbitrary in your stated case since your query would be selecting no actual points.

**Comment by jpolchlo** [comment]
I suppose it depends on what your model is.  If I just want a triangulation of the points I can see then, sure, the `bounds` behavior is for sure correct.  But, if I'm thinking of the domain of interest as the triangulation of all the points, then it's for sure wrong.  You may decide that PDAL's domain is only ever the point sample, in which case, it's appropriate to defer to other solutions.

And it's not that we can't develop an alternate means to query the points.  For sure we can, but it raises the chances that we'll need manual parsing of the EPT hierarchy to at least discover the resolutions that are available.  That's not remotely fatal, but it does imply some burden.  Given that the EPT reader already knows everything it needs to know for this use case, I thought it might be a convenient addition.  But it does run into the question of how often it will be of interest to be able to generate a "multiresolution" sample, and that's a legit question that I can't answer.
